name: Packages

on:
  push:
    branches:
    - main
    - dev
    - 'dev/**'
    paths:
    - 'packages/**'
    - 'root-packages/**'
    - 'x11-packages/**'
  pull_request:
    paths:
    - 'packages/**'
    - 'root-packages/**'
    - 'x11-packages/**'
  workflow_dispatch:
    inputs:
      packages:
        description: "A space-separated names of packages selected for rebuilding"
        required: true
      free-space:
        description: "Free space even if not building large package (useful when building a large number of packages)"
        type: boolean
        default: false

permissions: {} # none

concurrency:
  # if this is a PR event, group = "pr-<number>", otherwise group = run_id so it never collides with other runs
  group: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.run_id }}
  # only cancel in-progress when it’s a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    permissions:
      contents: read # actions/upload-artifact doesn't need contents: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target_arch: [aarch64, x86_64]
      fail-fast: false
    steps:
    - name: Clone repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 1000
    - name: Set process id limit for 32-bit builds depending on aosp-libs
      run: echo 65535 | sudo tee /proc/sys/kernel/pid_max

    - name: Lint packages
      run: |
        declare -a package_recipes=()
        for repo_path in $(jq --raw-output 'del(.pkg_format) | keys | .[]' repo.json); do
          repo=$(jq --raw-output '.["'${repo_path}'"].name' repo.json)
          if [ -f "./built_${repo}_packages.txt" ]; then
            package_recipes+=($(cat "./built_${repo}_packages.txt" | repo_path="${repo_path}" awk '{print ENVIRON["repo_path"]"/"$1"/build.sh"}'))
          fi
        done

        if [[ "${#package_recipes[@]}" -gt 0 ]]; then
          ./scripts/lint-packages.sh "${package_recipes[@]}"
        fi

  test-buildorder-random:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
    - name: Clone repository
      uses: actions/checkout@v6
    - name: Randomise buildorder.py test
      run: ./scripts/bin/test-buildorder-random
    - name: Randomise buildorder.py test (aarch64)
      env:
        TERMUX_ARCH: aarch64
      run: ./scripts/bin/test-buildorder-random
    - name: Randomise buildorder.py test (arm)
      env:
        TERMUX_ARCH: arm
      run: ./scripts/bin/test-buildorder-random
    - name: Randomise buildorder.py test (x86_64)
      env:
        TERMUX_ARCH: x86_64
      run: ./scripts/bin/test-buildorder-random
